const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('gamehub', {
  getConfig: () => ipcRenderer.invoke('config:get'),
  setConfig: (cfg) => ipcRenderer.invoke('config:set', cfg),
  pickFolder: () => ipcRenderer.invoke('dialog:pickFolder'),
  enableLocal: (libraryDir) => ipcRenderer.invoke('local:enable', { libraryDir }),
  pickExeFile: (defaultPath) => ipcRenderer.invoke('dialog:pickExeFile', defaultPath),
  getLibrary: () => ipcRenderer.invoke('library:get'),
  rescan: () => ipcRenderer.invoke('library:rescan'),
  checkUpdate: () => ipcRenderer.invoke('update:check'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  setUpdateToken: (t) => ipcRenderer.invoke('update:setToken', t),
  onUpdateStatus: (cb) => ipcRenderer.on('update:status', (e, d) => cb(d)),
  login: (username, password) => ipcRenderer.invoke('auth:login', { username, password }),
  logout: () => ipcRenderer.invoke('auth:logout'),
  authStatus: () => ipcRenderer.invoke('auth:status'),
  addToLibrary: (id) => ipcRenderer.invoke('mylib:add', id),
  removeFromLibrary: (id) => ipcRenderer.invoke('mylib:remove', id),
  toggleFavorite: (id) => ipcRenderer.invoke('fav:toggle', id),
  getCategories: () => ipcRenderer.invoke('cat:get'),
  saveCategories: (data) => ipcRenderer.invoke('cat:save', data),
  myStats: () => ipcRenderer.invoke('me:stats'),
  userStats: (id) => ipcRenderer.invoke('user:stats', id),
  leaderboard: () => ipcRenderer.invoke('social:leaderboard'),
  setAvatar: (avatar) => ipcRenderer.invoke('me:avatar', avatar),
  install: (id, packageId, installDir) => ipcRenderer.invoke('game:install', { gameId: id, packageId: packageId ?? id, installDir: installDir || null }),
  runInstaller: (id) => ipcRenderer.invoke('game:runInstaller', id),
  pickExe: (id) => ipcRenderer.invoke('game:pickExe', id),
  getCandidates: (id) => ipcRenderer.invoke('game:candidates', id),
  setExe: (id, exePath) => ipcRenderer.invoke('game:setExe', { gameId: id, exePath }),
  play: (id) => ipcRenderer.invoke('game:play', id),
  verifyInstall: (id) => ipcRenderer.invoke('game:verify', id),
  openFolder: (id) => ipcRenderer.invoke('game:openFolder', id),
  uninstall: (id) => ipcRenderer.invoke('game:uninstall', id),
  onTaskUpdate: (cb) => ipcRenderer.on('task:update', (e, data) => cb(data)),
  // themed dialogs: main asks, the renderer shows a Gamehub-styled modal
  onAsk: (cb) => ipcRenderer.on('ui:ask', (e, data) => cb(data)),
  answerAsk: (id, response) => ipcRenderer.send(`ui:answer:${id}`, response),
  winMinimize: () => ipcRenderer.invoke('win:minimize'),
  winMaximize: () => ipcRenderer.invoke('win:maximize'),
  winClose: () => ipcRenderer.invoke('win:close'),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
});
