const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('gamehub', {
  getConfig: () => ipcRenderer.invoke('config:get'),
  setConfig: (cfg) => ipcRenderer.invoke('config:set', cfg),
  pickFolder: () => ipcRenderer.invoke('dialog:pickFolder'),
  enableLocal: (storeDir, gamesDir) => ipcRenderer.invoke('local:enable', { storeDir, gamesDir }),
  configureLocal: (patch) => ipcRenderer.invoke('local:configure', patch),
  resetLocal: () => ipcRenderer.invoke('local:reset'),
  pickExeFile: (defaultPath) => ipcRenderer.invoke('dialog:pickExeFile', defaultPath),
  getLibrary: () => ipcRenderer.invoke('library:get'),
  rescan: () => ipcRenderer.invoke('library:rescan'),
  checkUpdate: () => ipcRenderer.invoke('update:check'),
  getUpdateStatus: () => ipcRenderer.invoke('update:status'),
  installUpdate: () => ipcRenderer.invoke('update:install'),
  onUpdateStatus: (cb) => ipcRenderer.on('update:status', (e, d) => cb(d)),
  login: (username, password) => ipcRenderer.invoke('auth:login', { username, password }),
  logout: () => ipcRenderer.invoke('auth:logout'),
  authStatus: () => ipcRenderer.invoke('auth:status'),
  addToLibrary: (id) => ipcRenderer.invoke('mylib:add', id),
  removeFromLibrary: (id) => ipcRenderer.invoke('mylib:remove', id),
  toggleFavorite: (id) => ipcRenderer.invoke('fav:toggle', id),
  getCategories: () => ipcRenderer.invoke('cat:get'),
  saveCategories: (data) => ipcRenderer.invoke('cat:save', data),
  myStats: () => ipcRenderer.invoke('me:stats'),
  userStats: (id) => ipcRenderer.invoke('user:stats', id),
  leaderboard: () => ipcRenderer.invoke('social:leaderboard'),
  setAvatar: (avatar) => ipcRenderer.invoke('me:avatar', avatar),
  install: (id, packageId, installDir) => ipcRenderer.invoke('game:install', { gameId: id, packageId: packageId ?? id, installDir: installDir || null }),
  installDlc: (id, packageId, parentGameId) => ipcRenderer.invoke('game:installDlc', { gameId: id, packageId: packageId ?? id, parentGameId }),
  applyUpdate: (id, packageId) => ipcRenderer.invoke('game:applyUpdate', { gameId: id, packageId }),
  pauseInstall: (id) => ipcRenderer.invoke('game:pause', id),
  resumeInstall: (id) => ipcRenderer.invoke('game:resume', id),
  cancelInstall: (id) => ipcRenderer.invoke('game:cancel', id),
  getDlc: (id) => ipcRenderer.invoke('game:dlc', id),
  runInstaller: (id) => ipcRenderer.invoke('game:runInstaller', id),
  pickExe: (id) => ipcRenderer.invoke('game:pickExe', id),
  getCandidates: (id) => ipcRenderer.invoke('game:candidates', id),
  setExe: (id, exePath) => ipcRenderer.invoke('game:setExe', { gameId: id, exePath }),
  play: (id) => ipcRenderer.invoke('game:play', id),
  verifyInstall: (id) => ipcRenderer.invoke('game:verify', id),
  openFolder: (id) => ipcRenderer.invoke('game:openFolder', id),
  uninstall: (id) => ipcRenderer.invoke('game:uninstall', id),
  onTaskUpdate: (cb) => ipcRenderer.on('task:update', (e, data) => cb(data)),
  // themed dialogs: main asks, the renderer shows a Gamehub-styled modal
  onAsk: (cb) => ipcRenderer.on('ui:ask', (e, data) => cb(data)),
  onAskDismiss: (cb) => ipcRenderer.on('ui:ask-dismiss', () => cb()),
  answerAsk: (id, response) => ipcRenderer.send(`ui:answer:${id}`, response),
  winMinimize: () => ipcRenderer.invoke('win:minimize'),
  winMaximize: () => ipcRenderer.invoke('win:maximize'),
  winClose: () => ipcRenderer.invoke('win:close'),
  openExternal: (url) => ipcRenderer.invoke('shell:openExternal', url),
  linuxDesktopStatus: () => ipcRenderer.invoke('linuxDesktop:status'),
  linuxDesktopInstall: () => ipcRenderer.invoke('linuxDesktop:install'),
  linuxDesktopRemove: () => ipcRenderer.invoke('linuxDesktop:remove'),
});
